const SET_SKIN = "SET_SKIN";
const UPDATE_SKIN = "UPDATE_SKIN";
const SET_CONTACT = "SET_CONTACT";
const UPDATE_CONTACT = "UPDATE_CONTACT";
const SET_EDUCATION = "SET_EDUCATION";
const UPDATE_EDUCATION = "UPDATE_EDUCATION";

export {
    SET_SKIN,
    UPDATE_SKIN,
    SET_CONTACT,
    UPDATE_CONTACT,
    SET_EDUCATION,
    UPDATE_EDUCATION
}